feat: Add first generic types (UserInfoResponse)
panva/node-openid-client pull request #324
Opened 2021-01-18 14:21 UTC by filipesmedeiros

By using generics, we can enforce proper type checking without the need of casting. This is just the first, because `[key: string]: unknown` is used some more in the type declarations.

2021-01-18 14:25 UTC, panva commented
Please make sure the PR contains no unnecessary changes such as changes to just padding, extra spaces, or quotation marks. Else this cannot be reviewed. Thank you.

2021-01-18 14:59 UTC, filipesmedeiros commented
Hey! Yeah I tried to be careful but I guess it slipped though anyway ahah, gonna fix it!

2021-01-18 15:53 UTC, filipesmedeiros commented
If you could check again, that would be awesome, thanks

2021-01-18 16:03 UTC, filipesmedeiros commented
I can't figure out why https://github.com/panva/node-openid-client/blob/main/types/openid-client-tests.ts#L112 uses the string `'some user info name'` there, but it's making the generics not work. What do you think @panva ?

2021-01-18 16:05 UTC, panva commented
> I can't figure out why [https://github.com/panva/node-openid-client/blob/main/types/openid-client-tests.ts#L112](https://github.com/panva/node-openid-client/blob/main/types/openid-client-tests.ts?rgh-link-date=2021-01-18T16%3A03%3A17Z#L112) uses the string `'some user info name'` there, but it's making the generics not work. What do you think @panva ?

because of `[key: string]: unknown;` on the current types. As i said in my earlier comment, your PR must be backwards compatible so the defaults you're assigning probably need to be `[key: string]: unknown;` too.

2021-01-18 16:26 UTC, filipesmedeiros commented
I understand, and did that. But imo (of course you can take it as you want) this TS change would be worth a major change. Generics should replace having `unknown`s. Of course, if you don't think so, we can just keep adding generics while keeping them there!

2021-01-18 16:34 UTC, panva commented
> I understand, and did that. But imo (of course you can take it as you want) this TS change would be worth a major change. Generics should replace having `unknown`s. Of course, if you don't think so, we can just keep adding generics while keeping them there!

I'm not on board with a new major just because of types. I think you should be able to keep the current behaviour and remove unknowns when one uses generics by having your `TUserInfo` default be `{ [key: string]: unknown; }` object.

2021-01-18 16:41 UTC, filipesmedeiros commented
> I think you should be able to keep the current behaviour and remove unknowns when one uses generics by having your TUserInfo default be { [key: string]: unknown; } object.

And then, to remove the unknowns, we just have to pass `{}` or something to the generic, right? That sounds great actually!

2021-01-18 16:47 UTC, panva commented
I think you're good to add tests of the generics now.

2021-01-19 13:14 UTC, filipesmedeiros commented
Hey @panva can you see if this is something you like?

2021-01-20 11:48 UTC, panva requested changes

2021-01-20 11:48 UTC, panva commented on types/openid-client-tests.ts
> +    console.log(userinfoGeneric.someProp);
```suggestion
    console.log(userinfoGeneric.someProp.toFixed(1));
```

2021-01-20 11:48 UTC, panva commented on types/openid-client-tests.ts
> +    console.log(userinfoAddressGeneric.address ? userinfoAddressGeneric.address.street : undefined);
```suggestion
    console.log(userinfoAddressGeneric.address ? userinfoAddressGeneric.address.street.substring(0) : undefined);
```

2021-01-20 11:48 UTC, panva commented on types/openid-client-tests.ts
> +    console.log(userinfoOverride.email_verified);
```suggestion
    console.log(userinfoOverride.email_verified.substring(0));
```

2021-01-20 11:56 UTC, merged

2021-01-20 11:57 UTC, panva commented
@filipesmedeiros thank you, keep 'em coming!

2021-01-20 13:00 UTC, filipesmedeiros commented
Nice! Thanks for the awesome package, do you have a prediction for when this can go live? Eheh
I'll try to finish the other generics when I have the time!

2021-01-20 13:02 UTC, panva commented
> do you have a prediction for when this can go live?

Unless a fix is needed in the meantime I will release a new minor version over the weekend.