Make static Issuer methods generic
panva/node-openid-client pull request #371
Opened 2021-05-31 09:59 UTC by mikaelkaron

Allows the client returned from either `Issuer<TClient>.discover` or `Issuer<TClient>.webfinger` to be generically typed.

2021-05-31 10:32 UTC, panva requested changes
Hi @mikaelkaron,

please make this a non-breaking change, e.g. by defaulting to the before used values and add tests verifying the updated functionality to `types/openid-client-tests.ts`

2021-05-31 10:52 UTC, mikaelkaron commented
Not really sure how I'd add tests for this type change. But it's now a non-breaking change.

2021-06-01 15:10 UTC, panva requested changes
Just missing tests in `types/openid-client-tests.ts` that would confirm the functionality and ensure future type changes don't break this addition.

2021-06-10 15:17 UTC, panva commented
Ping me here if you'd like this reopen after you've added the changes requested.

2021-06-10 15:17 UTC, closed without merging