Refactor issuer discovery
panva/node-openid-client pull request #637
Opened 2023-11-23 00:17 UTC by big-kahuna-burger

Just splits uri detection code from a call to discovery endpoint and avoids duplication

2023-11-27 09:11 UTC, panva requested changes
please move the `getUri` function to the root of the file, so that it's not part of the `discover` function

2023-11-27 10:35 UTC, panva requested changes

2023-11-27 10:35 UTC, panva commented on lib/issuer.js
> +    const wellKnownUri = getUri(uri);
```suggestion
    const wellKnownUri = resolveWellKnownUri(uri);
```

2023-11-27 10:35 UTC, panva commented on lib/issuer.js
> +function getUri(uri) {
```suggestion
function resolveWellKnownUri(uri) {
```

2023-12-06 13:48 UTC, big-kahuna-burger commented
@panva ptal

2023-12-06 14:45 UTC, panva approved these changes

2023-12-06 14:45 UTC, merged